from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class ILogger(Protocol):
    def debug(self, message: str, **context: Any) -> None: ...

    def info(self, message: str, **context: Any) -> None: ...

    def warning(self, message: str, **context: Any) -> None: ...

    def error(self, message: str, **context: Any) -> None: ...

    def exception(self, message: str, **context: Any) -> None: ...
